export const SELECTIONNER_SUJETS = "SELECTIONNER_SUJETS";
export const SELECTIONNER_LANGUAGES = "SELECTIONNER_LANGUAGES";
export const REPONDRE_QUESTION = "REPONDRE_QUESTION";
export const REINITIALISER_QUIZ = "REINITIALISER_QUIZ";
export const AJOUTER_QUIZ = "AJOUTER_QUIZ";
export const AJOUTER_QUIZ_PERSONNALISE = "AJOUTER_QUIZ_PERSONNALISE";